---
- name: copy undercloud config
  copy:
    src: /usr/share/instack-undercloud/undercloud.conf.sample
    dest: /home/stack/undercloud.conf

- name: deploy the thing
  command: /usr/bin/openstack undercloud install
