---
- name: get ironic uuid list
  shell: |
    source /home/stack/stackrc &&
    /bin/openstack baremetal node list -c UUID -f value
  register: ironic_uuid_list

- name: set ironic node power stat
  shell: |
    source /home/stack/stackrc && 
    /bin/openstack baremetal node power off {{ item }}
  with_items:
    - "{{ ironic_uuid_list.stdout_lines }}"

- name: configure boot mode for ironic nodes
  shell: |
    source /home/stack/stackrc &&
    /bin/openstack baremetal configure boot

- name: set ironic node managable stat
  shell: |
    source /home/stack/stackrc && 
    /bin/openstack baremetal node manage {{ item }}
  with_items:
    - "{{ ironic_uuid_list.stdout_lines }}"

- name: start introspection
  shell: |
    source /home/stack/stackrc &&
    /bin/openstack overcloud node introspect --all-manageable --provide
