---
- name: undercloud deploy
  include: deploy_undercloud.yml

- name: import ironic
  include: import_ironic.yml
  with_dict: "{{ ironic_nodes }}"

- name: ironic introspection
  include: ironic_introspection.yml

- name: node profiling
  include: node_profiling.yml
