---
- name: auto attach
  command: subscription-manager attach --auto
  when: RH_AUTO_ATTACH == 'yes'

- name: pool attach
  command: subscription-manager attach --pool={{ RH_POOL_ID }}
  when: RH_AUTO_ATTACH != 'yes' and RH_POOL_ID

- name: enable ocata repos
  command: subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms --enable rhel-7-server-rh-common-rpms --enable rhel-ha-for-rhel-7-server-rpms --enable rhel-7-server-openstack-11-rpms --enable rhel-7-server-openstack-11-devtools-rpms
  when: OPENSTACK_VERSION =='ocata'

- name: enable newton repos
  command: subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms --enable rhel-7-server-rh-common-rpms --enable rhel-ha-for-rhel-7-server-rpms --enable rhel-7-server-openstack-10-rpms --enable rhel-7-server-openstack-10-devtools-rpms
  when: OPENSTACK_VERSION=='newton'

- name: set RHEL release
  command: subscription-manager release --set {{ RHEL_VERSION }}
