---
- name: Add root pub key to stack user
  authorized_key:
    user: stack
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: yum update all
  yum:
    name: '*'
    state: latest

- name: restart undercloud
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: wait for server {{ ansible_ssh_host | default(inventory_hostname) }} to come back online
  wait_for:
    port: 22
    state: started
    host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
    delay: 30
    sleep: 10
  delegate_to: localhost

<<<<<<< HEAD
- name: install libguestfs-tools
  yum:
    name: libguestfs-tools
    state: latest
  when: BUILD_DPDK_IMAGE == 'yes'

=======
>>>>>>> 693307c1bce2732d4ec88236af776207a381b3be
- name: install tripleo client
  yum:
    name: python-tripleoclient
    state: latest

- name: install apache 
  yum:
    name: httpd
    state: latest

- name: start apache
  service:
    enabled: yes
    name: httpd
    state: started

- name: create contrail repo directory
  file:
    path: /var/www/html/contrail
    state: directory
    mode: 0755

- name: extract contrail package
  unarchive:
    src: "{{ CONTRAIL_PACKAGE_LOCATION }}/contrail-install-packages_{{ CONTRAIL_VERSION }}-{{ CONTRAIL_VERSION_BUILD }}-{{ OPENSTACK_VERSION }}.tgz"
    dest: /var/www/html/contrail
    remote_src: true

- name: add contrail repository
  yum_repository:
    name: contrail
    description: contrail rep
<<<<<<< HEAD
    baseurl: http://{{ ansible_ssh_host }}/contrail
=======
    baseurl: http://localhost/contrail
>>>>>>> 693307c1bce2732d4ec88236af776207a381b3be
    gpgcheck: no

- name: install contrail tripleo heat templates
  yum:
    name: contrail-tripleo-heat-templates
    state: latest
    disable_gpg_check: yes

- name: install contrail tripleo puppet modules
  yum:
    name: contrail-tripleo-puppet
    state: latest
    disable_gpg_check: yes

- name: install contrail puppet modules
  yum:
    name: contrail-tripleo-puppet
    state: latest
    disable_gpg_check: yes

- name: get rhosp-director-images
  yum:
    name: rhosp-director-images
    state: latest

- name: get rhosp-director-images-ipa
  yum:
    name: rhosp-director-images
    state: latest
