## A Heat environment file which can be used to set up storage
#params for storage-environment
## backends. Defaults to Ceph used as a backend for Cinder, Glance and

## Nova ephemeral storage.
resource_registry:
  OS::TripleO::Services::CephMon: /home/stack/openstack-tripleo-heat-templates/puppet/services/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /home/stack/openstack-tripleo-heat-templates/puppet/services/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /home/stack/openstack-tripleo-heat-templates/puppet/services/ceph-client.yaml
  OS::TripleO::NodeUserData: wipe-disks.yaml

parameter_defaults:

  #### BACKEND SELECTION ####

  ## Whether to enable iscsi backend for Cinder.
  CinderEnableIscsiBackend: {{ CinderEnableIscsiBackend }}
  ## Whether to enable rbd (Ceph) backend for Cinder.
  CinderEnableRbdBackend: {{ CinderEnableRbdBackend }}
  ## Cinder Backup backend can be either 'ceph' or 'swift'.
  CinderBackupBackend: {{ CinderBackupBackend }}
  ## Whether to enable NFS backend for Cinder.
  # CinderEnableNfsBackend: false
  ## Whether to enable rbd (Ceph) backend for Nova ephemeral storage.
  NovaEnableRbdBackend: {{ NovaEnableRbdBackend }}
  ## Glance backend can be either 'rbd' (Ceph), 'swift' or 'file'.
  GlanceBackend: {{ GlanceBackend }}
  ## Gnocchi backend can be either 'rbd' (Ceph), 'swift' or 'file'.
  GnocchiBackend: {{ GnocchiBackend }}

  ceph_disks: "{{ ceph_disks|join(' ') }}"
  ExtraConfig:
    ceph::profile::params::osds:
    {% for disk in ceph_disks %}
         '{{ disk }}': {}
    {% endfor %}

    ceph::osd_crush_update_on_start: {{ osd_crush_update_on_start }}
    ceph::profile::params::osd_journal_size: {{ osd_journal_size }}

    CephPools:
    {% for pool in ceph_pools %}
  {{ pool }}:
        size: {{ replica_size }}
        pg_num: {{ final_pgp_num }}
        pgp_num: {{ final_pgp_num }}
    {% endfor %}
