---
OPENSTACK_CONTROLLER_COUNT: 3
CONTRAIL_CONTROLLER_COUNT: 3
CONTRAIL_ANALYTICS_COUNT: 3
CONTRAIL_ANALYTICS_DB_COUNT: 3
CONTRAIL_TSN_COUNT: 0
COMPUTE_COUNT: 0
COMPUTE_DPDK_COUNT: 4
QEMU: true
CONTRAIL_REPO: http://192.168.24.1/contrail
EC2METADATAIP: 192.168.24.1
DNS_SERVERS: 10.87.64.101
NTP_SERVER: 10.0.0.1
CONTRAIL_PHY_INTERFACE: eth1
CONTRAIL_VROUTER_GW: 10.0.0.1
CONTRAIL_VROUTER_NETMASK: 255.255.255.0
CONTROLPLANE_INTERFACE: eth0
EXTERNAL_INTERFACE: vlan10
VROUTER_PARENT_VLAN_INTERFACE:
VROUTER_BOND_INTERFACE:
VROUTER_BOND_MEMBERS:
contrail_networks:
- ControlPlane:
    PrefixLength: 24
    Prefix: 192.168.24.0
- InternalApi:
    PrefixLength: 24
    Prefix: 10.0.0.0
    Gateway: 10.0.0.1
    VlanId: 1
    AllocationStart: 10.0.0.11
    AllocationEnd: 10.0.0.200
- External:
    PrefixLength: 24
    Prefix: 10.1.0.0
    VlanId: 10
    AllocationStart: 10.1.0.11
    AllocationEnd: 10.1.0.200
- Management:
    PrefixLength: 24
    Prefix: 10.2.0.0
    VlanId: 20
    AllocationStart: 10.2.0.11
    AllocationEnd: 10.2.0.200
- Storage:
    PrefixLength: 24
    Prefix: 10.3.0.0
    VlanId: 30
    AllocationStart: 10.3.0.11
    AllocationEnd: 10.3.0.200
- StorageMgmt:
    PrefixLength: 24
    Prefix: 10.4.0.0
    VlanId: 40
    AllocationStart: 10.4.0.11
    AllocationEnd: 10.4.0.200
controller_nic_layout:
- nic1:
    Network: ControlPlane
    Routes:
      - ip_netmask: 169.254.169.254/32
        next_hop: 192.168.24.1
    DnsServer: true
- nic2:
    Network: InternalApi
    Routes:
      - default: true
- nic3:
    Network: None
- vlan10:
    Network: External
    VlanParent: nic3
- vlan20:
    Network: Management
    VlanParent: nic3
- vlan30:
    Network: Storage
    VlanParent: nic3
- vlan40:
    Network: StorageMgmt
    VlanParent: nic3

compute_nic_layout:
- nic1:
    Network: ControlPlane
    Routes:
      - ip_netmask: 169.254.169.254/32
        next_hop: 192.168.24.1
    DnsServer: true
- nic2:
    Network: None
- vhost0:
    Network: InternalApi
    Routes:
      - default: true
- nic3:
    Network: None
- vlan10:
    Network: External
    VlanParent: nic3
- vlan20:
    Network: Management
    VlanParent: nic3
- vlan30:
    Network: Storage
    VlanParent: nic3
- vlan40:
    Network: StorageMgmt
    VlanParent: nic3
